---
title: "Total Soccer"
output: html_document
date: "2024-09-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = F,
                      warning = F)
```

```{r}
rm(list=ls())
library(tidyverse)
library(jsonlite)
library(openxlsx)
source("D:/wangxiaoyang/Regular_Work/support_files/get_day_span_program_sheet.R")
source("D:/wangxiaoyang/Regular_Work/support_files/other_functions.R")

channel_mapping = read.csv("D:/wangxiaoyang/Regular_Work/support_files/channel_mapping.csv")

tar_info = read.csv("D:/wangxiaoyang/Regular_Work/support_files/target_digits.csv")
tar_info$Target <- lapply(tar_info$Target, fromJSON)
tar_info$Var_Dig <- lapply(tar_info$Var_Dig, fromJSON)
```

```{r}
convert_time <- function(x) {
  total_seconds <- as.numeric(x) * 86400
  hours <- floor(total_seconds / 3600)
  minutes <- floor((total_seconds %% 3600) / 60)
  seconds <- round(total_seconds %% 60)
  
  x <- sprintf("%02d:%02d:%02d", hours, minutes, seconds)
  
  return(x)
}
```


```{r}
df_org = read.xlsx('./天下足球_看视频.xlsx')
df_org = df_org %>%
  mutate(Date = as.Date(as.numeric(Date), origin = "1899-12-30"),
         Dur = End - Start,
         Start = sapply(Start, convert_time),
         End = sapply(End, convert_time),
         Dur = sapply(Dur, convert_time),
         Channel = "CCTV-5",
         Regions = "China National",
         Weekday = "Monday"
         )

df = df_org %>% 
  filter(
    Date <= "2024-10-21",
    Date > "2024-10-15",
    League != ""
  ) %>% 
  mutate(
    ProgramID = paste(Date, Start, Title)
  ) %>%
  left_join(channel_mapping, 
            join_by(Channel == channel))

res = with(df,
           paste(format(as.Date(Date, format="%Y-%m-%d"), "%Y%m%d"),
                 gsub(" ", 0, sprintf("%04s", code)),
                 gsub(" ", 0, gsub(":", "", sprintf("%08s", Start))),
                 gsub(" ", 0, gsub(":", "", sprintf("%08s", End))),
                 ProgramID
           ) )

write.table(res,
            './total_soccer_ps.txt',
            row.names = F,
            col.names = F,
            quote = F,
            fileEncoding = "GBK")
```

```{r}
data = read.csv("./data.csv")
data = data[-1, ]
colnames(data)[1] = "ProgramID"

df_final = df %>% 
  left_join(
    data,
    "ProgramID"
  ) %>% 
  mutate(
    Title_Eng = case_when(
      Title == "德甲集锦" ~ "Bundesliga Highlights",
      Title == "英超集锦" ~ "EPL Highlights",
      Title == "天下足球" ~ "Total Soccer",
      Title == "西甲集锦" ~ "La Liga Highlights",
      .default = ""
    )
  )
```

```{r}
df_res = df_final %>% 
  select(
    Title_Eng, Dur, Regions,
    Title, Channel, Date, Weekday,
    Start, End,
    all_of(12:16),
    League
  )

time_columns <- c("Start", "End", "Dur")

seconds_in_a_day <- 24 * 3600

for (col in time_columns) {
  df_res[[col]] <- sapply(df_res[[col]], convert_to_excel_time)
}
```

```{r}
filter_out_empty = function(df, league) {
  total_soccers = which(df$League == "Total Soccer")
  keep = c()
  for (i in 2:length(total_soccers)) {
    not_empty = FALSE
    for (j in seq(total_soccers[i-1], total_soccers[i]-1)) {
      if (df$League[j] == league) {
        not_empty = TRUE
      }
    }
    keep = c(keep, not_empty)
  }
  
  not_empty = FALSE
  for (k in total_soccers[length(total_soccers)]:dim(df)[1]) {
    if (df$League[k] == league) {
        not_empty = TRUE
      }
  }
  keep = c(keep, not_empty)
  
  total_soccers_drop = total_soccers[!keep]
  df = df[-total_soccers_drop, ]
  return(df)
}
```


```{r}
tar_info_ger = tar_info %>% 
  filter(
    Other == "Bundesliga-Match"
  ) %>% 
  select(Var_Dig)
tar_info_ger = tar_info_ger[[1]][[1]]

digits_ger = tar_info_ger$Digit[1:5]
digits_ger
```

```{r}
df_esp = df_res %>% 
  filter(
    League %in% c("ESP", "Total Soccer")
  )
for (i in 1:length(digits_ger)) {
  df_esp[, 10+i-1] = round(as.numeric(df_esp[, 10+i-1]), digits_ger[i])
}

# df_esp = filter_out_empty(df_esp, "ESP")
```

```{r}
df_ger = df_res %>% 
  filter(
    League %in% c("GER", "Total Soccer")
  )
for (i in 1:length(digits_ger)) {
  df_ger[, 10+i-1] = round(as.numeric(df_ger[, 10+i-1]), digits_ger[i])
}

# df_ger = filter_out_empty(df_ger, "GER")
```

```{r}
tar_info_epl = tar_info %>% 
  filter(
    Other == "EPL-Match"
  ) %>% 
  select(Var_Dig)
tar_info_epl = tar_info_epl[[1]][[1]]

digits_epl = tar_info_epl$Digit[1:5]
digits_epl
```

```{r}
df_epl = df_res %>% 
  filter(
    League %in% c("EPL", "Total Soccer")
  )
for (i in 1:length(digits_epl)) {
  df_epl[, 10+i-1] = round(as.numeric(df_epl[, 10+i-1]), digits_epl[i])
}

# df_epl = filter_out_empty(df_epl, "EPL")
```

```{r}
df_res_digit = rbind(df_esp, df_epl, df_ger) %>% 
  select( -League )
write.xlsx(df_res_digit, "./result.xlsx")
```
